version: "3.9"

services:
  csdc26bb-discord-bot:
    ports:
      - 9191:8080
    build:
      dockerfile: ./Dockerfile
    networks:
      - backend
    environment:
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SETTINGS_DISCORD_TOKEN=${SETTINGS_DISCORD_TOKEN}
    restart: always

networks:
  backend:
    driver: bridge
    external: false
