spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/UNRATED_SKINS?useSSL=false"
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

logging.level:
  org: info
  at.template: info
  com.zaxxer.hikari: info
