name: Deployment Workflow
on:
  push:
    branches: [main]

jobs:
  job_one:
    name: Deploy Discord Bot
    environment: deploy
    runs-on: ["self-hosted", "csdc26bb"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
      - name: Check status
        run: ls -alht && git status
      - name: Builder Containers
        run: sudo docker compose build
      - name: Stop and remove old containers
        run: sudo docker compose down --remove-orphans
      - name: Start new containers
        run: sudo docker compose up -d
      - name: Delete secrets
        run: rm ./.env
